# Generated by Django 6.0.3 on 2026-03-10 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='שם הקורס')),
                ('course_number', models.CharField(blank=True, max_length=50, verbose_name='מספר קורס')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='שם המוסד')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='כותרת הקובץ')),
                ('file', models.FileField(upload_to='documents/', verbose_name='קובץ')),
                ('category', models.CharField(choices=[('summary', 'סיכום'), ('exam', 'מבחן עבר'), ('hw', 'תרגיל בית'), ('other', 'אחר')], max_length=20, verbose_name='סוג חומר')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='תאריך העלאה')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course', verbose_name='קורס')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='הועלה על ידי')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.university', verbose_name='אוניברסיטה'),
        ),
    ]
