# Generated by Django 6.0.3 on 2026-04-12 14:23

import core.utils
import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='שם מלא')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='אימייל (אופציונלי)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='staff_images/', validators=[core.utils.validate_file_size], verbose_name='תמונה')),
                ('average_rating', models.FloatField(default=0.0, verbose_name='דירוג ממוצע')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='שם הקורס')),
                ('course_number', models.CharField(blank=True, max_length=50, verbose_name='מספר קורס')),
                ('year', models.IntegerField(blank=True, choices=[(1, "שנה א'"), (2, "שנה ב'"), (3, "שנה ג'"), (4, "שנה ד'"), (5, 'תואר שני')], null=True, verbose_name='שנת לימוד')),
                ('semester', models.CharField(choices=[('A', "סמסטר א'"), ('B', "סמסטר ב'"), ('summer', 'סמסטר קיץ'), ('yearly', 'שנתי')], default='A', max_length=10, verbose_name='סמסטר')),
                ('track', models.CharField(default='general', max_length=50, verbose_name='מסלול התמחות')),
                ('description', models.TextField(blank=True, verbose_name='תיאור הקורס')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='מספר צפיות')),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='שם המקצוע')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='תוכן הפוסט')),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts_images/', validators=[core.utils.validate_file_size])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='שם המוסד')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='university_logos/', validators=[core.utils.validate_file_size], verbose_name='לוגו המוסד')),
                ('brand_color', models.CharField(default='#0d6efd', max_length=7, verbose_name='צבע מותג')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(error_messages={'unique': 'משתמש עם שם זה כבר קיים במערכת.'}, max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='שם משתמש יכול להכיל אותיות, מספרים, רווחים, ותווים מיוחדים (@/./+/-/_).', regex='^[\\w.@+\\- ]+$')])),
                ('role', models.CharField(choices=[('member', 'חבר/ת קהילה'), ('moderator', 'איש/אשת צוות'), ('admin', 'מנהל/ת העל')], default='member', max_length=15, verbose_name='תפקיד המשתמש')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('academicstaff_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.academicstaff')),
                ('title', models.CharField(default='מרצה', max_length=50, verbose_name='תואר')),
            ],
            bases=('core.academicstaff',),
        ),
        migrations.CreateModel(
            name='TeachingAssistant',
            fields=[
                ('academicstaff_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.academicstaff')),
                ('title', models.CharField(default='מתרגל', max_length=50, verbose_name='תואר')),
            ],
            bases=('core.academicstaff',),
        ),
        migrations.CreateModel(
            name='AgentKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='agent_storage/', validators=[core.utils.validate_file_size])),
                ('course_name', models.CharField(max_length=100, verbose_name='שיוך לקורס')),
                ('extracted_text', models.TextField(blank=True, null=True, verbose_name='תוכן הטקסט שחולץ')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_knowledge', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='שם קבוצה (אופציונלי)')),
                ('participants', models.ManyToManyField(related_name='chat_rooms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='כותרת הקובץ')),
                ('file', models.FileField(upload_to='documents/', validators=[core.utils.validate_file_size])),
                ('file_content', models.TextField(blank=True, null=True, verbose_name='תוכן הקובץ לחיפוש')),
                ('file_extension', models.CharField(blank=True, max_length=10)),
                ('file_size_bytes', models.PositiveIntegerField(default=0)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('personal_tag', models.CharField(choices=[('none', 'ללא תיוג'), ('urgent', 'חומר עזר'), ('exam', 'למבחן'), ('summary', 'סיכום'), ('important', 'חשוב')], default='none', max_length=20, verbose_name='תיוג אישי')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.course')),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_documents', to=settings.AUTH_USER_MODEL)),
                ('staff_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.academicstaff', verbose_name='מרצה/מתרגל רלוונטי')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.chatroom')),
                ('attached_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.document')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DocumentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DownloadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_date', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='כותרת')),
                ('link', models.URLField(blank=True, null=True, verbose_name='קישור חיצוני')),
                ('file', models.FileField(blank=True, null=True, upload_to='external_resources/', verbose_name='קובץ מקומי')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('personal_tag', models.CharField(choices=[('none', 'ללא תיוג'), ('urgent', 'חומר עזר'), ('exam', 'למבחן'), ('summary', 'סיכום'), ('important', 'חשוב')], default='none', max_length=20, verbose_name='תיוג אישי')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_resources', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='feedbacks/', validators=[core.utils.validate_file_size])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False, verbose_name='טופל?')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='שם התיקייה')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('color', models.CharField(default='#ffc107', max_length=10, verbose_name='צבע')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='core.course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='core.folder')),
                ('staff_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.academicstaff', verbose_name='איש סגל')),
            ],
            options={
                'unique_together': {('course', 'parent', 'name')},
            },
        ),
        migrations.AddField(
            model_name='document',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.folder'),
        ),
        migrations.AddField(
            model_name='course',
            name='major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.major', verbose_name='מקצוע'),
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='שם הקהילה')),
                ('description', models.TextField(blank=True, verbose_name='תיאור')),
                ('community_type', models.CharField(choices=[('global', 'כלל ארצי'), ('university', 'אוניברסיטה'), ('major', 'מסלול לימודים'), ('year', 'שנתון ספציפי'), ('custom', 'קהילה חופשית (עתידי)')], default='custom', max_length=20)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('members', models.ManyToManyField(blank=True, related_name='joined_communities', to=settings.AUTH_USER_MODEL)),
                ('major', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.major')),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.university')),
            ],
        ),
        migrations.CreateModel(
            name='MarketplacePost',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.post')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('category', models.CharField(choices=[('rent', 'השכרת דירה'), ('sell', 'מכירה'), ('giveaway', 'מסירה')], default='sell', max_length=20)),
            ],
            bases=('core.post',),
        ),
        migrations.CreateModel(
            name='VideoPost',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.post')),
                ('youtube_url', models.URLField(default='https://www.youtube.com', max_length=500, validators=[django.core.validators.RegexValidator(message='נא להזין קישור תקין מיוטיוב (למשל: https://www.youtube.com/watch?v=...)', regex='^(https?\\:\\/\\/)?(www\\.youtube\\.com|youtu\\.be)\\/.+$')], verbose_name='קישור ליוטיוב')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='video_thumbnails/', validators=[core.utils.validate_file_size])),
            ],
            bases=('core.post',),
        ),
        migrations.AddField(
            model_name='post',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='core.community', verbose_name='קהילה'),
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='תגובה')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.post')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('friend_request', 'בקשת חברות'), ('system', 'התראת מערכת')], default='system', max_length=20)),
                ('title', models.CharField(max_length=255, verbose_name='כותרת')),
                ('message', models.TextField(verbose_name='הודעה')),
                ('link', models.CharField(blank=True, max_length=500, null=True, verbose_name='קישור')),
                ('is_read', models.BooleanField(default=False, verbose_name='נקרא?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='core.university'),
        ),
        migrations.AddField(
            model_name='major',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.university', verbose_name='אוניברסיטה'),
        ),
        migrations.AddField(
            model_name='academicstaff',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.university', verbose_name='אוניברסיטה'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, choices=[(1, "שנה א'"), (2, "שנה ב'"), (3, "שנה ג'"), (4, "שנה ד'"), (5, "שנה ה' / תואר שני")], null=True, verbose_name='שנת לימוד')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='קצת עלי (Bio)')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/', validators=[core.utils.validate_file_size], verbose_name='תמונת פרופיל')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='מספר טלפון')),
                ('current_balance', models.PositiveIntegerField(default=0, verbose_name='יתרת מטבעות לשימוש')),
                ('lifetime_coins', models.PositiveIntegerField(default=0, verbose_name='מוניטין (סך כל המטבעות שהורווחו מעשייה)')),
                ('theme_preference', models.CharField(choices=[('light', 'יום (בהיר)'), ('dark', 'לילה (כהה)'), ('auto', 'אוטומטי')], default='auto', max_length=10, verbose_name='ערכת נושא')),
                ('language_preference', models.CharField(choices=[('he', 'עברית'), ('en', 'English')], default='he', max_length=10, verbose_name='שפה')),
                ('profile_visibility', models.CharField(choices=[('public', 'כולם יכולים לראות את הפרופיל שלי'), ('users_only', 'רק משתמשים מחוברים יכולים לראות'), ('private', 'אף אחד (פרופיל פרטי)')], default='public', max_length=20, verbose_name='מי יכול לראות את הפרופיל שלי')),
                ('show_coins_publicly', models.BooleanField(default=True, verbose_name='הצג מוניטין לציבור')),
                ('referral_code', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('favorite_courses', models.ManyToManyField(blank=True, related_name='favorited_by_users', to='core.course', verbose_name='קורסים מועדפים')),
                ('major', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.major', verbose_name='מסלול לימודים')),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to=settings.AUTH_USER_MODEL)),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.university', verbose_name='מוסד לימודים')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseSemesterStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.IntegerField(verbose_name='שנה אקדמית')),
                ('semester', models.CharField(choices=[('A', 'סמסטר א׳'), ('B', 'סמסטר ב׳'), ('summer', 'סמסטר קיץ')], max_length=10, verbose_name='סמסטר')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_staff', to='core.course')),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.academicstaff')),
            ],
            options={
                'unique_together': {('course', 'academic_year', 'semester', 'staff_member')},
            },
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'ממתין לאישור'), ('accepted', 'חברים'), ('blocked', 'חסום')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to=settings.AUTH_USER_MODEL)),
                ('user_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user_from', 'user_to')},
            },
        ),
        migrations.CreateModel(
            name='StaffReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='דירוג')),
                ('review_text', models.TextField(verbose_name='חוות דעת')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.academicstaff', verbose_name='איש סגל')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('staff_member', 'user')},
            },
        ),
        migrations.CreateModel(
            name='UserCourseSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_starred', models.BooleanField(default=False, verbose_name='מסומן בכוכב')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_by_users', to='core.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_selections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='core.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'document')},
            },
        ),
    ]
