# Generated by Django 6.0.3 on 2026-03-12 21:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='שם הקורס')),
                ('course_number', models.CharField(blank=True, max_length=50, verbose_name='מספר קורס')),
                ('year', models.IntegerField(blank=True, choices=[(1, "שנה א'"), (2, "שנה ב'"), (3, "שנה ג'"), (4, "שנה ד'"), (5, 'תואר שני')], null=True, verbose_name='שנת לימוד')),
                ('semester', models.CharField(choices=[('A', "סמסטר א'"), ('B', "סמסטר ב'"), ('summer', 'סמסטר קיץ'), ('yearly', 'שנתי')], default='A', max_length=10, verbose_name='סמסטר')),
                ('track', models.CharField(choices=[('general', 'כללי / קורס חובה (ללא מסלול)'), ('ee_communication', 'חשמל: תקשורת, מידע וסייבר'), ('ee_energy', 'חשמל: מערכות וניהול אנרגיה'), ('ee_electromagnetics', 'חשמל: אלקטרומגנטיות ומיקרוגלים'), ('ee_vlsi', 'חשמל: התקני מוליכים למחצה ו-VLSI'), ('ee_control', 'חשמל: בקרה'), ('ee_computers', 'חשמל: מחשבים'), ('ee_signal_processing', 'חשמל: עיבוד אותות'), ('ee_electro_optics', 'חשמל: אלקטרואופטיקה'), ('cs_general', 'מדמ"ח: מסלול כללי'), ('cs_software', 'מדמ"ח: הנדסת תוכנה'), ('cs_cyber', 'מדמ"ח: סייבר ואבטחת מידע'), ('cs_ai', 'מדמ"ח: בינה מלאכותית (AI) ומערכות לומדות'), ('cs_data', 'מדמ"ח: מדע הנתונים (Data Science)'), ('iem_is', 'תעשייה וניהול: מערכות מידע'), ('iem_data', 'תעשייה וניהול: מדע הנתונים ואנליטיקה'), ('iem_supply_chain', 'תעשייה וניהול: תפעול ולוגיסטיקה'), ('iem_human_factors', 'תעשייה וניהול: הנדסת אנוש'), ('mech_robotics', 'מכונות: מכטרוניקה ורובוטיקה'), ('mech_thermofluids', 'מכונות: זרימה ואנרגיה'), ('mech_solid', 'מכונות: מכניקה וחומרים'), ('mech_design', 'מכונות: תכן וייצור'), ('civil_structures', 'אזרחית: הנדסת מבנים'), ('civil_management', 'אזרחית: ניהול וביצוע הבנייה'), ('civil_geotech', 'אזרחית: גאוטכניקה'), ('civil_transportation', 'אזרחית: הנדסת תחבורה'), ('civil_water', 'אזרחית: הנדסת מים וסביבה')], default='general', max_length=50, verbose_name='מסלול התמחות')),
                ('description', models.TextField(blank=True, verbose_name='תיאור/סילבוס קצר')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='מספר צפיות')),
            ],
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='שם המרצה/מתרגל')),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='שם המקצוע')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='שם המוסד')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='נושא (תקלה/הצעה)')),
                ('message', models.TextField(verbose_name='הודעה')),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='feedbacks/', verbose_name='צילום מסך (אופציונלי)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False, verbose_name='טופל?')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='משתמש')),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='שם התיקייה')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('color', models.CharField(choices=[('#ffc107', 'צהוב קלאסי'), ('#0d6efd', 'כחול'), ('#198754', 'ירוק'), ('#dc3545', 'אדום'), ('#6c757d', 'אפור')], default='#ffc107', max_length=10, verbose_name='צבע התיקייה')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='core.course', verbose_name='שייך לקורס')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='נוצר על ידי')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='core.folder', verbose_name='תיקיית אב')),
            ],
            options={
                'unique_together': {('course', 'parent', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='כותרת הקובץ')),
                ('file', models.FileField(upload_to='documents/', verbose_name='קובץ')),
                ('file_extension', models.CharField(blank=True, max_length=10, verbose_name='סיומת הקובץ')),
                ('file_size_bytes', models.PositiveIntegerField(default=0, verbose_name='גודל הקובץ בבתים')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='מספר הורדות')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='העלה באופן אנונימי')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course', verbose_name='קורס (שיוך כללי)')),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_documents', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.folder', verbose_name='באיזו תיקייה?')),
                ('lecturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.lecturer', verbose_name='מרצה/מתרגל רלוונטי (לא חובה)')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='major',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.major', verbose_name='מקצוע'),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('broken', 'קובץ פגום/לא נפתח'), ('inappropriate', 'תוכן לא ראוי'), ('irrelevant', 'לא רלוונטי לקורס'), ('wrong_place', 'מיקום לא נכון'), ('outdated', 'לא מעודכן')], max_length=20)),
                ('description', models.TextField(blank=True, verbose_name='פירוט נוסף')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='major',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.university', verbose_name='אוניברסיטה'),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.university', verbose_name='אוניברסיטה'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, choices=[(1, "שנה א'"), (2, "שנה ב'"), (3, "שנה ג'"), (4, "שנה ד'"), (5, "שנה ה' / תואר שני")], null=True)),
                ('drive_coins', models.PositiveIntegerField(default=0, verbose_name='מטבעות דרייב')),
                ('theme_preference', models.CharField(choices=[('light', 'יום (בהיר)'), ('dark', 'לילה (כהה)')], default='light', max_length=10, verbose_name='ערכת נושא')),
                ('language_preference', models.CharField(choices=[('he', 'עברית'), ('en', 'English')], default='he', max_length=10, verbose_name='שפה')),
                ('show_coins_publicly', models.BooleanField(default=True, verbose_name='הצג את המטבעות שלי בטבלת האלופים')),
                ('major', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.major')),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.university')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseSemesterLecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.IntegerField(verbose_name='שנה אקדמית')),
                ('semester', models.CharField(choices=[('A', 'סמסטר א׳'), ('B', 'סמסטר ב׳'), ('summer', 'סמסטר קיץ')], max_length=10, verbose_name='סמסטר')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_lecturers', to='core.course')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.lecturer')),
            ],
            options={
                'unique_together': {('course', 'academic_year', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='LecturerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='דירוג (1-5)')),
                ('review_text', models.TextField(verbose_name='חוות דעת')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.course', verbose_name='באיזה קורס?')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.lecturer', verbose_name='מרצה')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='סטודנט מדרג')),
            ],
            options={
                'unique_together': {('lecturer', 'user')},
            },
        ),
    ]
