# Generated by Django 6.0.3 on 2026-03-12 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='brand_color',
            field=models.CharField(default='#0d6efd', help_text='קוד צבע Hex (לדוגמה: #ff0000 לאדום)', max_length=7, verbose_name='צבע מותג'),
        ),
        migrations.AddField(
            model_name='university',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='university_logos/', verbose_name='לוגו המוסד'),
        ),
    ]
