# Generated by Django 6.0.3 on 2026-03-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='year',
            field=models.IntegerField(blank=True, choices=[(1, 'שנה א'), (2, 'שנה ב'), (3, 'שנה ג'), (4, 'שנה ד')], null=True, verbose_name='שנת לימוד'),
        ),
    ]
