# Generated by Django 6.0.3 on 2026-03-21 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='downloadlog',
            old_name='downloaded_at',
            new_name='download_date',
        ),
    ]
