# Generated by Django 6.0.3 on 2026-04-29 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDeletionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך מחיקה')),
                ('reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='סיבת עזיבה (אופציונלי)')),
            ],
            options={
                'ordering': ['-deleted_at'],
            },
        ),
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, verbose_name='שם הפריט')),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('category', models.CharField(max_length=80, verbose_name='קטגוריה')),
                ('description', models.TextField(blank=True, verbose_name='תיאור')),
                ('price_coins', models.PositiveIntegerField(verbose_name='מחיר במטבעות')),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop_items/', verbose_name='תמונה')),
                ('badge_label', models.CharField(blank=True, default='', max_length=40, verbose_name='תווית')),
                ('redemption_code', models.CharField(blank=True, default='', max_length=120, verbose_name='קוד/שובר')),
                ('redemption_instructions', models.TextField(blank=True, default='', verbose_name='הוראות מימוש')),
                ('stock_quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='מלאי')),
                ('is_featured', models.BooleanField(default=False, verbose_name='מוצג בראש החנות')),
                ('is_active', models.BooleanField(default=True, verbose_name='פעיל')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='סדר תצוגה')),
            ],
            options={
                'verbose_name': 'פריט בחנות',
                'verbose_name_plural': 'פריטי חנות',
                'ordering': ['sort_order', '-is_featured', 'price_coins', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_query', models.CharField(max_length=255, verbose_name='מילת חיפוש')),
                ('result_count', models.IntegerField(default=0, verbose_name='מספר תוצאות שנמצאו')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShopPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_name', models.CharField(max_length=120, verbose_name='שם פריט')),
                ('category', models.CharField(max_length=80, verbose_name='קטגוריה')),
                ('coins_spent', models.PositiveIntegerField(verbose_name='עלות במטבעות')),
                ('delivery_code', models.CharField(blank=True, default='', max_length=120, verbose_name='קוד/שובר שנמסר')),
                ('delivery_instructions', models.TextField(blank=True, default='', verbose_name='הוראות שנמסרו')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='core.shopitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'רכישה מהחנות',
                'verbose_name_plural': 'רכישות חנות',
                'ordering': ['-created_at'],
            },
        ),
    ]
