# Generated by Django 6.0.3 on 2026-04-18 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='uploader_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='כתובת IP של המעלה'),
        ),
        migrations.AlterField(
            model_name='downloadlog',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='core.document'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('friend_request', 'בקשת חברות'), ('system', 'התראת מערכת'), ('economy', 'פעולה כספית')], default='system', max_length=20),
        ),
        migrations.CreateModel(
            name='BountyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('reward_amount', models.PositiveIntegerField(default=0)),
                ('is_fulfilled', models.BooleanField(default=False)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bounty_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CoinTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.IntegerField(verbose_name='amount')),
                ('transaction_type', models.CharField(choices=[('signup', 'Signup'), ('referral', 'Referral'), ('quality_bonus', 'Quality bonus'), ('ai_summary', 'AI summary'), ('bounty', 'Bounty'), ('purchase', 'Purchase'), ('system', 'System'), ('spend', 'Spend')], default='system', max_length=30)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('balance_before', models.IntegerField(blank=True, null=True)),
                ('balance_after', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
