# Generated by Django 6.0.3 on 2026-03-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_downloaded_at_downloadlog_download_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadlog',
            name='download_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
