# Generated by Django 6.0.3 on 2026-03-19 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_conversation_message'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='community',
            unique_together={('university', 'major', 'community_type')},
        ),
    ]
