# Generated by Django 6.0.3 on 2026-03-12 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_university_brand_color_university_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='lecturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='folders', to='core.lecturer', verbose_name='מרצה/מתרגל (אופציונלי)'),
        ),
    ]
