# Generated by Django 6.0.3 on 2026-04-30 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_accountdeletionlog_shopitem_searchlog_shoppurchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audio_files/', verbose_name='קובץ אודיו')),
                ('text_used', models.TextField(blank=True, help_text='ערך התייחסות של 500 התווים הראשונים', null=True, verbose_name='טקסט שהשתמשנו בו')),
                ('is_generated', models.BooleanField(default=False, verbose_name='האם נוצר בהצלחה')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='תאריך עדכון')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audio', to='core.document')),
            ],
            options={
                'verbose_name': 'אודיו מסמך',
                'verbose_name_plural': 'אודיו מסמכים',
            },
        ),
    ]
