# Generated by Django 6.0.3 on 2026-03-29 23:58

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notification_usercourseselection'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('internal', 'קובץ פנימי'), ('external', 'קובץ חיצוני')], default='internal', max_length=10),
        ),
        migrations.AddField(
            model_name='document',
            name='external_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='קישור חיצוני'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/internal/', validators=[core.utils.validate_file_size]),
        ),
        migrations.DeleteModel(
            name='AgentKnowledge',
        ),
    ]
