# Generated by Django 6.0.3 on 2026-03-30 00:12

import core.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_document_document_type_document_external_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='document_type',
        ),
        migrations.RemoveField(
            model_name='document',
            name='external_url',
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(default='', upload_to='documents/', validators=[core.utils.validate_file_size]),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ExternalResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='כותרת')),
                ('link', models.URLField(blank=True, null=True, verbose_name='קישור חיצוני')),
                ('file', models.FileField(blank=True, null=True, upload_to='external_resources/', verbose_name='קובץ מקומי')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_resources', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
