# Generated by Django 6.0.3 on 2026-03-21 00:59

import core.utils
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_community_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.AlterUniqueTogether(
            name='community',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='videopost',
            name='video_file',
        ),
        migrations.AddField(
            model_name='videopost',
            name='youtube_url',
            field=models.URLField(default='https://www.youtube.com', max_length=500, validators=[django.core.validators.RegexValidator(message='נא להזין קישור תקין מיוטיוב (למשל: https://www.youtube.com/watch?v=...)', regex='^(https?\\:\\/\\/)?(www\\.youtube\\.com|youtu\\.be)\\/.+$')], verbose_name='קישור ליוטיוב'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='documents/', validators=[core.utils.validate_file_size]),
        ),
        migrations.CreateModel(
            name='AgentKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='agent_storage/', validators=[core.utils.validate_file_size])),
                ('course_name', models.CharField(max_length=100, verbose_name='שיוך לקורס')),
                ('extracted_text', models.TextField(blank=True, null=True, verbose_name='תוכן הטקסט שחולץ')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_knowledge', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
