# Generated by Django 6.0.3 on 2026-03-20 19:24

import core.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='community',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='videopost',
            name='video_file',
        ),
        migrations.AddField(
            model_name='videopost',
            name='youtube_url',
            field=models.URLField(default='https://youtube.com', max_length=500, validators=[
                django.core.validators.RegexValidator(
                    message='נא להזין קישור תקין מיוטיוב (למשל: https://www.youtube.com/watch?v=...)',
                    regex='^(https?\\:\\/\\/)?(www\\.youtube\\.com|youtu\\.be)\\/.+$')], verbose_name='קישור ליוטיוב'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='documents/', validators=[core.utils.validate_file_size]),
        ),
    ]
