# Generated by Django 6.0.3 on 2026-05-01 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_documentaudio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AgentKnowledge',
        ),
    ]
