# Generated by Django 6.0.3 on 2026-03-10 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_course_university_alter_document_upload_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='מספר צפיות'),
        ),
        migrations.AddField(
            model_name='document',
            name='download_count',
            field=models.PositiveIntegerField(default=0, verbose_name='מספר הורדות'),
        ),
    ]
