# Generated by Django 6.0.3 on 2026-03-21 15:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_downloadlog_download_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadlog',
            name='download_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
