# Generated by Django 6.0.3 on 2026-03-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_folder_lecturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='default_anonymous_upload',
            field=models.BooleanField(default=False, verbose_name='העלה קבצים באופן אנונימי כברירת מחדל'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_data_request',
            field=models.DateTimeField(blank=True, null=True, verbose_name='תאריך בקשת מידע אחרונה'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_visibility',
            field=models.CharField(choices=[('public', 'כולם יכולים לראות את הפרופיל שלי'), ('users_only', 'רק משתמשים מחוברים יכולים לראות'), ('private', 'אף אחד (פרופיל פרטי)')], default='public', max_length=20, verbose_name='מי יכול לראות את הפרופיל שלי'),
        ),
    ]
