# Generated by Django 6.0.3 on 2026-04-18 20:03

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_notification_content_type_notification_object_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='documents/', validators=[core.utils.validate_file_size, core.utils.validate_file_type]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='theme_preference',
            field=models.CharField(choices=[('light', 'יום (בהיר)'), ('dark', 'לילה (כהה)')], default='auto', max_length=10, verbose_name='ערכת נושא'),
        ),
    ]
