# Generated by Django 6.0.3 on 2026-03-30 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_document_document_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='personal_tag',
            field=models.CharField(choices=[('none', 'ללא תיוג'), ('urgent', 'דחוף!'), ('exam', 'למבחן'), ('summary', 'סיכום מעולה'), ('important', 'חשוב מאוד')], default='none', max_length=20, verbose_name='תיוג אישי'),
        ),
        migrations.AddField(
            model_name='externalresource',
            name='personal_tag',
            field=models.CharField(choices=[('none', 'ללא תיוג'), ('urgent', 'דחוף!'), ('exam', 'למבחן'), ('summary', 'סיכום מעולה'), ('important', 'חשוב מאוד')], default='none', max_length=20, verbose_name='תיוג אישי'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
