# Generated by Django 6.0.3 on 2026-03-21 11:20

import core.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_message_conversation_remove_message_sender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicstaff',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='staff_images/', validators=[core.utils.validate_file_size], verbose_name='תמונה'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='feedbacks/', validators=[core.utils.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts_images/', validators=[core.utils.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='university',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='university_logos/', validators=[core.utils.validate_file_size], verbose_name='לוגו המוסד'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/', validators=[core.utils.validate_file_size], verbose_name='תמונת פרופיל'),
        ),
        migrations.AlterField(
            model_name='videopost',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='video_thumbnails/', validators=[core.utils.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='videopost',
            name='youtube_url',
            field=models.URLField(default='https://www.youtube.com', max_length=500, validators=[django.core.validators.RegexValidator(message='נא להזין קישור תקין מיוטיוב (למשל: https://www.youtube.com/watch?v=...)', regex='^(https?\\:\\/\\/)?(www\\.youtube\\.com|youtu\\.be)\\/.+$')], verbose_name='קישור ליוטיוב'),
        ),
    ]
