# Generated by Django 6.0.3 on 2026-03-11 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_course_view_count_document_download_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_anonymous',
            field=models.BooleanField(default=False, verbose_name='העלה באופן אנונימי (הסתר את שמי)'),
        ),
    ]
