# Generated by Django 6.0.3 on 2026-03-30 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_document_personal_tag_externalresource_personal_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='personal_tag',
            field=models.CharField(choices=[('none', 'ללא תיוג'), ('urgent', 'חומר עזר'), ('exam', 'למבחן'), ('summary', 'סיכום'), ('important', 'חשוב')], default='none', max_length=20, verbose_name='תיוג אישי'),
        ),
        migrations.AlterField(
            model_name='externalresource',
            name='personal_tag',
            field=models.CharField(choices=[('none', 'ללא תיוג'), ('urgent', 'חומר עזר'), ('exam', 'למבחן'), ('summary', 'סיכום'), ('important', 'חשוב')], default='none', max_length=20, verbose_name='תיוג אישי'),
        ),
    ]
