# Generated by Django 6.0.3 on 2026-03-13 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_userprofile_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='year',
            field=models.IntegerField(blank=True, choices=[(1, "שנה א'"), (2, "שנה ב'"), (3, "שנה ג'"), (4, "שנה ד'"), (5, "שנה ה' / תואר שני")], null=True, verbose_name='שנת לימוד'),
        ),
    ]
