# Generated by Django 6.0.3 on 2026-03-13 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_userprofile_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='default_anonymous_upload',
            field=models.BooleanField(default=False, verbose_name='העלה קבצים באופן אנונימי כברירת מחדל'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='language_preference',
            field=models.CharField(choices=[('he', 'עברית'), ('en', 'English')], default='he', max_length=10, verbose_name='שפה'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_visibility',
            field=models.CharField(choices=[('public', 'כולם יכולים לראות את הפרופיל שלי'), ('users_only', 'רק משתמשים מחוברים יכולים לראות'), ('private', 'אף אחד (פרופיל פרטי)')], default='public', max_length=20, verbose_name='מי יכול לראות את הפרופיל שלי'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='theme_preference',
            field=models.CharField(choices=[('light', 'יום (בהיר)'), ('dark', 'לילה (כהה)'), ('auto', 'אוטומטי')], default='auto', max_length=10, verbose_name='ערכת נושא'),
        ),
    ]
