# Generated by Django 6.0.3 on 2026-04-08 13:08

import core.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_document_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='agent_storage/', validators=[core.utils.validate_file_size])),
                ('course_name', models.CharField(max_length=100, verbose_name='שיוך לקורס')),
                ('extracted_text', models.TextField(blank=True, null=True, verbose_name='תוכן הטקסט שחולץ')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_knowledge', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
