# Generated by Django 6.0.3 on 2026-03-15 20:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_userprofile_phone_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='שם מלא')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='אימייל (אופציונלי)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='staff_images/', verbose_name='תמונה')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.university', verbose_name='אוניברסיטה')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='lecturerreview',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='lecturerreview',
            name='lecturer',
        ),
        migrations.RemoveField(
            model_name='lecturerreview',
            name='user',
        ),
        migrations.RemoveField(
            model_name='document',
            name='lecturer',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='lecturer',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='id',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='university',
        ),
        migrations.AddField(
            model_name='lecturer',
            name='title',
            field=models.CharField(default='מרצה', max_length=50, verbose_name='תואר'),
        ),
        migrations.CreateModel(
            name='TeachingAssistant',
            fields=[
                ('academicstaff_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.academicstaff')),
                ('title', models.CharField(default='מתרגל', max_length=50, verbose_name='תואר')),
            ],
            bases=('core.academicstaff',),
        ),
        migrations.AddField(
            model_name='document',
            name='staff_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.academicstaff', verbose_name='מרצה/מתרגל רלוונטי'),
        ),
        migrations.AddField(
            model_name='folder',
            name='staff_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.academicstaff', verbose_name='איש סגל'),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='academicstaff_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.academicstaff'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CourseSemesterStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.IntegerField(verbose_name='שנה אקדמית')),
                ('semester', models.CharField(choices=[('A', 'סמסטר א׳'), ('B', 'סמסטר ב׳'), ('summer', 'סמסטר קיץ')], max_length=10, verbose_name='סמסטר')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_staff', to='core.course')),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.academicstaff')),
            ],
            options={
                'unique_together': {('course', 'academic_year', 'semester', 'staff_member')},
            },
        ),
        migrations.CreateModel(
            name='StaffReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='דירוג')),
                ('review_text', models.TextField(verbose_name='חוות דעת')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.academicstaff', verbose_name='איש סגל')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('staff_member', 'user')},
            },
        ),
        migrations.DeleteModel(
            name='CourseSemesterLecturer',
        ),
        migrations.DeleteModel(
            name='LecturerReview',
        ),
    ]
