# Generated by Django 6.0.3 on 2026-04-08 14:00

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_agentknowledge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='documents/', validators=[core.utils.validate_file_size]),
        ),
    ]
