# Generated by Django 6.0.3 on 2026-04-10 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_document_file_agentknowledge'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_content',
            field=models.TextField(blank=True, null=True, verbose_name='תוכן הקובץ לחיפוש'),
        ),
    ]
