# Generated by Django 6.0.3 on 2026-03-17 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_userprofile_phone_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='user',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='university',
        ),
        migrations.RemoveField(
            model_name='lecturerreview',
            name='lecturer',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='lecturer',
        ),
        migrations.RemoveField(
            model_name='document',
            name='lecturer',
        ),
        migrations.AlterUniqueTogether(
            name='lecturerreview',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='lecturerreview',
            name='user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='major',
        ),
        migrations.RemoveField(
            model_name='post',
            name='university',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favorite_courses',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='core.course', verbose_name='קורסים מועדפים'),
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='שם הקהילה')),
                ('description', models.TextField(blank=True, verbose_name='תיאור')),
                ('community_type', models.CharField(choices=[('global', 'כלל ארצי'), ('university', 'אוניברסיטה'), ('major', 'מסלול לימודים'), ('year', 'שנתון ספציפי'), ('custom', 'קהילה חופשית (עתידי)')], default='custom', max_length=20)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('major', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.major')),
                ('members', models.ManyToManyField(blank=True, related_name='joined_communities', to=settings.AUTH_USER_MODEL)),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.university')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='core.community', verbose_name='קהילה'),
        ),
        migrations.DeleteModel(
            name='CourseSemesterLecturer',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='Lecturer',
        ),
        migrations.DeleteModel(
            name='LecturerReview',
        ),
    ]
