# Generated by Django 6.0.3 on 2026-03-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_academicstaff_alter_lecturerreview_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favorite_courses',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='core.course', verbose_name='קורסים מועדפים'),
        ),
    ]
