# Generated by Django 6.0.3 on 2026-04-12 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_document_file'),
        ('core', '0013_alter_comment_options_remove_comment_document_and_more'),
    ]

    operations = [
    ]
